# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Justina' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Justina
  pod 'Pulley'


  target 'JustinaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JustinaUITests' do
    # Pods for testing
  end

end
